### ISSUE TITLE
Build failed: multiple definition of `readbuf'

### ISSUE THREAD

**Issue by dimich-dmb** [stefanct/ch341eepromtool#1]
```
$  gcc -o ch341eeprom ch341eeprom.c ch341funcs.c -lusb-1.0
...
 /usr/bin/ld: /tmp/cca8HDsQ.o:(.bss+0x10): multiple definition of `readbuf'; /tmp/cc7ZTqAU.o:(.bss+0x10): first defined here
 collect2: error: ld returned 1 exit status
```
One `readbuf` definition is in ch341funcs.c at line 33. Another one is in ch341eeprom.c line 32. Should one of them be `extern` or `static`?

**Comment by df8oe** [comment]
I think you saw this issue at an Arch AUR update... Here the same. But: Why there is an update if the version stays at 0.5 and this repo has only one (initial) commit which is ~5 years ago?

**Comment by stefanct** [comment]
Hi everybody. I have initially put this code up because it wasn't available in a git repo while working on https://github.com/flashrom/flashrom. I have never intended to maintain it or anything (and from what I remember the code quality wasn't that great). Therefore, all issues are WONTFIX in this repo. Feel free to clone it and work on it. If someone wants to maintain it I can transfer this repo to someone else so that all previous links forward there. Until then I'll disable the issues.

Just a minor comment on this very problem: I have not looked at it but the reason this makes problems now and not earlier might be a change in compilers. However, if it is an error now it was probably wrong from the beginning and should be fixed. GL
